### ISSUE TITLE
希望可以加入 缩略图 切换功能

### ISSUE THREAD

**Issue by huanshiwushuang** [zhangzhengyi12/image-preview-vue#8]
希望可以加入 缩略图 切换功能

类似：https://www.17sucai.com/pins/demo-show?id=10443

**Comment by zhangzhengyi12** [comment]
感谢你的意见，我觉得是个不错的想法，近期会施工的

**Comment by huanshiwushuang** [comment]
> 我仔细考量了一下觉得缩略图功能可能更加适合非全屏查看图片的地方，会占用相当的图片显示面积，造成内容的拥挤

额额  我已经选择使用了  v-viewer 了 谢谢你的回答
